# Generated by Django 3.2.6 on 2021-08-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20210825_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='lname',
        ),
    ]
