# Generated by Django 3.2.6 on 2021-08-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20210825_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUS',
            new_name='Contact',
        ),
    ]
