# Generated by Django 3.2.6 on 2021-08-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_rename_contactus_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telephone',
        ),
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.CharField(choices=[('RL', 'Relationship'), ('LC', 'Life Coaching'), ('LR', 'Leadership'), ('TM', 'Team Managament')], default='Life coaching', max_length=300),
        ),
    ]
